name: risto_widgets_example
description: "Demonstrates how to use the risto_widgets plugin."
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  risto_widgets:
    path: ../

  flutter_bloc: ^9.1.1
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.9

  latlong2: ^0.9.1

dependency_overrides:
  package_info_plus:
    path: ../packages/package_info_plus

  geolocator_linux:
    path: ../packages/geolocator_linux

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true