documentation:
  - any:
      - '.github/**/*'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

test:
  - any:
      - 'test/**/*'

example:
  - any:
      - 'example/**/*'

android:
  - any:
      - 'android/**/*'

workflows:
  - any:
      - '.github/workflows/**/*'

lib:
  - any:
      - 'lib/**/*'