import 'package:flutter/material.dart';
import 'package:risto_widgets/risto_widgets.dart';

class ListTileButtonPage extends StatelessWidget {
  const ListTileButtonPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('List Tile Buttons')),
      body: ListView(
        padding: const EdgeInsets.all(16.0),
        children: [
          Text('Core ListTile Buttons', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            body: const Text('List Tile Button with Elevation'),
            subtitle: const Text('Subtitle Text'),
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.blue,
            elevation: 4.0,
            trailing: const Icon(Icons.arrow_forward),
            minHeight: 90,
          ),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            body: const Text('List Tile Button without Elevation'),
            subtitle: const Text('Subtitle Text'),
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.blue,
            trailing: const Icon(Icons.arrow_forward),
          ),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            body: const Text('List Tile Button with icon'),
            backgroundColor: Colors.white,
            subtitle: const Text('Without action'),
            trailing: Icon(Icons.error, size: 18, color: theme.iconTheme.color),
            leading: const Icon(Icons.info, color: Colors.blue),
            leadingSizeFactor: 1.5,
          ),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            body: const Text('List Tile Button center'),
            subtitle: const Text('Disabled'),
            backgroundColor: Colors.white,
            elevation: 2,
            trailing: Icon(Icons.error, size: 18, color: theme.iconTheme.color),
            leading: const Icon(Icons.info, color: Colors.blue),
            contentAlignment: Alignment.center,
            leadingSizeFactor: 1.5,
            disabled: true,
          ),
          ListTileButton(
            onPressed: () => {},
            backgroundColor: Colors.white,
            leading: const Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Text("21"),
                Padding(padding: EdgeInsets.only(top: 2.0), child: Text("Sep")),
              ],
            ),
            leadingSizeFactor: 2,
            trailing: const Icon(Icons.arrow_forward),
            subtitle: const Text('Subtitle Text'),
            body: const Text('List Tile Button column leading'),
          ),

          const SizedBox(height: 24),
          Text('IconListTile Buttons', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),

          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text('Icon List Tile with Elevation'),
            icon: Icons.star,
            subtitle: const Text('Subtitle Text'),
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.purple,
            iconColor: Colors.purple,
            elevation: 4.0,
            trailing: const Icon(Icons.arrow_forward),
            leadingSizeFactor: 2.0,
          ),
          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text('Icon List Tile without Elevation'),
            icon: Icons.star_border,
            subtitle: const Text('Subtitle Text'),
            onPressed: () {},
            backgroundColor: Colors.transparent,
            elevation: 1,
            shadowColor: Colors.transparent,
            borderColor: Colors.purple,
            iconColor: Colors.purple,
            trailing: const Icon(Icons.arrow_forward),
            leadingSizeFactor: 1.0,
          ),

          const SizedBox(height: 24),
          Text('Elevation & Custom Shadows', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            body: const Text(
              'High Elevation, Colored Shadow',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            subtitle: const Text('shadowColor: Colors.purple'),
            onPressed: () {},
            backgroundColor: Colors.white,
            elevation: 8.0,
            shadowColor: Colors.purple,
            trailing: const Icon(
              Icons.wb_cloudy_outlined,
              color: Colors.purple,
            ),
          ),
          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text('Subtle Deep Shadow'),
            icon: Icons.layers,
            subtitle: const Text('elevation: 12.0, shadowColor: Colors.black'),
            onPressed: () {},
            backgroundColor: Colors.white,
            elevation: 12.0,
            shadowColor: Colors.black,
            trailing: const Icon(Icons.arrow_forward_ios, size: 16),
            leadingSizeFactor: 1.5,
          ),

          const SizedBox(height: 24),
          Text('Sizing Constraints', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            width: 250,
            height: 100,
            body: const Text('Fixed Width & Height'),
            subtitle: const Text('width: 250, height: 100'),
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.teal,
            elevation: 2.0,
            contentAlignment: Alignment.center,
          ),
          ListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            maxWidth: 300,
            minHeight: 80,
            body: const Text('Max Width & Min Height'),
            subtitle: const Text(
              'maxWidth: 300, minHeight: 80\nStretches vertically if content is long, but width is clamped.',
            ),
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.teal,
            elevation: 2.0,
          ),
          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text('Custom Min Height (40)'),
            icon: Icons.compress,
            onPressed: () {},
            backgroundColor: Colors.white,
            borderColor: Colors.teal,
            iconColor: Colors.teal,
            minHeight: 40,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          ),

          const SizedBox(height: 24),
          Text('Gradient List Tile Buttons', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),
          ListTileButton(
            body: const Text('List Tile Button with Gradient'),
            subtitle: const Text('Enabled — uses backgroundGradient'),
            onPressed: () {},
            backgroundColor: Colors.white,
            backgroundGradient: const LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [Color(0xFF7F7FFF), Color(0xFFB76DFF)],
            ),
            borderColor: Colors.transparent,
            elevation: 3,
            trailing: const Icon(Icons.chevron_right),
            minHeight: 80,
          ),
          const SizedBox(height: 16),
          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text(
              'Gradient with Elevation & Shadow',
              style: TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
            subtitle: const Text(
              'Shadows now work flawlessly under gradients!',
              style: TextStyle(color: Colors.white70),
            ),
            icon: Icons.auto_awesome,
            onPressed: () {},
            backgroundColor: Colors.white,
            backgroundGradient: const LinearGradient(
              colors: [Colors.orange, Colors.deepOrange],
            ),
            borderColor: Colors.transparent,
            iconColor: Colors.white,
            elevation: 6.0,
            shadowColor: Colors.deepOrange,
            trailing: const Icon(Icons.star_border, color: Colors.white),
            leadingSizeFactor: 1.4,
          ),
          const SizedBox(height: 16),
          IconListTileButton(
            margin: const EdgeInsets.symmetric(vertical: 8),
            title: const Text('Icon List Tile with Disabled Gradient'),
            subtitle: const Text('Disabled — uses disabledBackgroundGradient'),
            icon: Icons.lock,
            onPressed: () {},
            disabled: true,
            backgroundColor: Colors.white,
            backgroundGradient: const LinearGradient(
              colors: [Color(0xFF00C6FF), Color(0xFF0072FF)],
            ),
            disabledBackgroundGradient: const LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [Color(0xFFBBBBBB), Color(0xFF888888)],
            ),
            borderColor: Colors.grey.shade300,
            iconColor: Colors.white,
            elevation: 2.0,
            shadowColor: Colors.black26,
            trailing: const Icon(Icons.block, color: Colors.white),
            leadingSizeFactor: 1.4,
            padding: const EdgeInsets.symmetric(horizontal: 12),
            bodyPadding: const EdgeInsets.symmetric(horizontal: 8),
            contentAlignment: Alignment.centerLeft,
            minHeight: 70,
          ),

          const SizedBox(height: 24),
          Text('Double List Tile Buttons', style: theme.textTheme.titleLarge),
          const SizedBox(height: 16),
          DoubleListTileButtons(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
            space: 16.0,
            firstButton: ListTileButton(
              margin: const EdgeInsets.only(right: 8.0),
              body: const Center(
                child: Text(
                  'First Button with Elevation',
                  textAlign: TextAlign.center,
                ),
              ),
              onPressed: () {},
              backgroundColor: Colors.red.shade100,
              elevation: 4.0,
              shadowColor: Colors.red,
            ),
            secondButton: ListTileButton(
              margin: const EdgeInsets.only(left: 8.0),
              body: const Center(
                child: Text(
                  'Second Button with Elevation',
                  textAlign: TextAlign.center,
                ),
              ),
              onPressed: () {},
              backgroundColor: Colors.green.shade100,
              elevation: 4.0,
              shadowColor: Colors.green,
            ),
          ),
          DoubleListTileButtons(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
            space: 16.0,
            firstButton: ListTileButton(
              margin: const EdgeInsets.only(right: 8.0),
              body: const Center(child: Text('First Button without Elevation')),
              onPressed: () {},
              backgroundColor: Colors.red,
            ),
            secondButton: ListTileButton(
              margin: const EdgeInsets.only(left: 8.0),
              body: const Center(
                child: Text('Second Button without Elevation'),
              ),
              onPressed: () {},
              backgroundColor: Colors.green,
            ),
          ),
          SizedBox(
            width: MediaQuery.of(context).size.width * 0.75,
            height: MediaQuery.of(context).size.height * 0.065,
            child: DoubleListTileButtons(
              space: 10,
              firstButton: IconListTileButton(
                onPressed: () {},
                icon: Icons.school,
                iconColor: Colors.white,
                title: Text(
                  'Profile',
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: Colors.white,
                  ),
                ),
                backgroundColor: Colors.blueAccent,
                borderRadius: 19 * 2,
                margin: EdgeInsets.zero,
                padding: EdgeInsets.zero,
                leadingPadding: const EdgeInsets.only(
                  left: 10 / 2,
                  right: 10 / 3,
                ),
                bodyPadding: EdgeInsets.zero,
                contentAlignment: Alignment.center,
              ),
              secondButton: IconListTileButton(
                onPressed: () {},
                icon: Icons.restaurant_menu,
                iconColor: Colors.white,
                title: Text(
                  'Absent',
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: Colors.white,
                  ),
                ),
                backgroundColor: Colors.red,
                borderRadius: 19 * 2,
                margin: EdgeInsets.zero,
                padding: EdgeInsets.zero,
                leadingPadding: const EdgeInsets.only(
                  left: 10 / 2,
                  right: 10 / 3,
                ),
                bodyPadding: EdgeInsets.zero,
                contentAlignment: Alignment.center,
              ),
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }
}
