name: Coverage Badge & Web Report

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  coverage-and-deploy:
    name: Coverage & Deploy Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Generate HTML & Badge SVG
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          
          genhtml -o coverage coverage/lcov.info
          
          COVERAGE_PERCENT=$(lcov --summary coverage/lcov.info | grep "lines......" | grep -o '[0-9.]*%' | tr -d '%')
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV
          
          curl -o coverage-badge.svg "https://img.shields.io/badge/Coverage-${COVERAGE_PERCENT}%25-brightgreen.svg"
          mkdir -p .github/badges/
          mv coverage-badge.svg .github/badges/coverage-badge.svg

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'coverage'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Generate GitHub App Token
        id: generate_pr_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.ORG_CI_APP_ID }}
          private-key: ${{ secrets.ORG_CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Push Badge to coverage branch
        run: |
          # 1. Configuriamo il bot
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 2. Creiamo o ci spostiamo sul branch 'coverage'
          git checkout -B coverage
          
          # 3. Aggiungiamo solo il badge SVG
          git add -f .github/badges/coverage-badge.svg
          
          # 4. Facciamo il commit (se non ci sono modifiche, non fallisce)
          git commit -m "chore: Update coverage badge [skip ci]" || echo "No changes to commit"
          
          # 5. Autentichiamo Git con il token della nostra App e forziamo il push
          git remote set-url origin https://x-access-token:${{ steps.generate_pr_token.outputs.token }}@github.com/${{ github.repository }}.git
          git push origin coverage --force