name: "PR Labeler"
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ORG_CI_APP_ID }}
          private-key: ${{ secrets.ORG_CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Apply Labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ steps.generate_token.outputs.token }}"
          sync-labels: true